name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag my-image:$(date +%s)
      
    - name: Login to DockerHub
    - uses: docker/login-action@v2
    - with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       
    - uses: actions/checkout@v3
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node_dock
